OfficeGroceries.Admin/Controllers/Settings/CompanyAddressesController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using NuIngredient.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System.Web.Routing;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.IO;

namespace NuIngredient.Controllers
{
    [Authorize]
    public class CompanyAddressesController : GridController<CompanyAddress, CompanyAddressViewModel>
    {

        public CompanyAddressesController()
            : base(new CompanyAddressRepository(), new CompanyAddressMapper())
        {

        }

        [AcceptVerbs(HttpVerbs.Post)]
        public JsonResult Read([DataSourceRequest]DataSourceRequest request, string companyID)
        {
            var list = _repo.Read().Where(p => p.CompanyID.ToString() == companyID).ToList().Select(p => _mapper.MapToViewModel(p));
            return Json(list.ToDataSourceResult(request));
        }

        public override JsonResult Read([DataSourceRequest] DataSourceRequest request)
        {
            var list = _repo.Read().Where(p => p.CompanyID == CurrentUser.CompanyID).ToList().Select(p => _mapper.MapToViewModel(p));
            return Json(list.ToDataSourceResult(request));
        }


        public JsonResult DropDownCompanyAddresses()
        {
            var addresses = _repo.Read().Where(a => a.CompanyID == CurrentUser.CompanyID)
                .OrderBy(t => t.Name).ToArray()
                .Select(a => new SelectItemViewModel
                {
                    ID = a.ID.ToString(),
                    Name = string.Format("{0} {1} {2}", a.Address1, a.Address2, a.Postcode)
                }
            ).ToList();

            addresses.Insert(0, new SelectItemViewModel { ID = null, Name = string.Format("{0} {1} {2}", CurrentUser.Company.Address1, CurrentUser.Company.Address2, CurrentUser.Company.Postcode) });
                
            return Json(addresses, JsonRequestBehavior.AllowGet);
        }

    }

}

OfficeGroceries.Admin/Controllers/Settings/CustomerSettingsController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using NuIngredient.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System.Web.Routing;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Mail;
using NuIngredient.Models.Extenstions;

namespace NuIngredient.Controllers
{
    [Authorize]
    public class CustomerSettingsController : BaseController
    {
        CompanyRepository _repo = new CompanyRepository();
        CompanyMapper _mapper = new CompanyMapper();
        // GET: Settings
        [HttpGet]
        public ActionResult _EditCustomerDetails()
        {
            var viewModel = _mapper.MapToViewModel(CurrentUser.Company);
            return PartialView(viewModel);
        }

        [HttpPost]
        public ActionResult _EditCustomerDetails(CompanyViewModel viewModel)
        {
            var model = _repo.Find(Guid.Parse(viewModel.ID));

            SendCustomerDetailChangeEmail(model, viewModel);
            _mapper.MapToModel(viewModel, model);
            _repo.Update(model, new string[] { "Name", "Address1", "Postcode", "Telephone", "Email", "DeliveryInstruction" });
            ViewBag.Saved = true;

            return PartialView(_mapper.MapToViewModel(model));
        }

        public void SendCustomerDetailChangeEmail(Company before, CompanyViewModel after)
        {
            var changeLog = string.Empty;
            changeLog += AddDifference("Name", before.Name, after.Name);
            changeLog += AddDifference("Delivery Address", before.Address1, after.Address1);
            changeLog += AddDifference("Postcode", before.Postcode, after.Postcode);
            changeLog += AddDifference("Telephone", before.Telephone, after.Telephone);
            changeLog += AddDifference("Email", before.Email, after.Email);
            changeLog += AddDifference("Delivery Instruction", before.DeliveryInstruction, after.DeliveryInstruction);

            if (changeLog == string.Empty) return;

            using (var context = new SnapDbContext())
            {
                var mailServer = context.EmailSettings.First();
                var overallSetting = context.Settings.First();
                MailMessage mailMessage = new MailMessage();
                mailMessage.Subject = String.Format("Detail Change from {0} ({1})", before.Name, before.AccountNo);
                mailMessage.AddToEmails(overallSetting.FeedbackCenterEmail);
                mailMessage.From = new MailAddress(mailServer.Email);
                mailMessage.Body = String.Format("<div class=\"row\" style='max-width: 500px;'>" +
                                                    "Customer Feedback" +
                                                    "<hr />" +
                                                    "<table>" +
                                                        changeLog +
                                                    "</table>" +
                                                    "<hr />" +
                                                "</div>");
                mailMessage.IsBodyHtml = true;

                // Send to feedback center
                EmailService.SendEmail(mailMessage, Server);
            }
        }

        private string AddDifference(string label, string before, string after)
        {
            if (before == after)
                return string.Empty;

            var str = "<tr>" +
                          "<td>" +
                              "<label>" + label + ":</label>" +
                          "</td>" +
                          "<td>" +
                              before +
                          "</td>" +
                          "<td>" +
                              after +
                          "</td>" +
                      "</tr>";
            return str;
        }
    }
}

OfficeGroceries.Admin/Controllers/Settings/HolidayGridController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using NuIngredient.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System.Web.Routing;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.IO;

namespace NuIngredient.Controllers
{
    [Authorize(Roles = "NI-User")]
    public class HolidayGridController : GridController<Holiday, HolidayGridViewModel>
    {
        public HolidayGridController()
            :base(new HolidayRepository(), new HolidayGridMapper())
        {

        }

        public override JsonResult Read(DataSourceRequest request)
        {
            var models = _repo.Read().Where(x => x.SupplierID == null).OrderByDescending(s => s.Date);
            var viewModels = models.ToList().Select(s => _mapper.MapToViewModel(s));

            return Json(viewModels.ToDataSourceResult(request));
        }

        public JsonResult ReadSupplierHolidays([DataSourceRequest] DataSourceRequest request, Guid supplierID)
        {
            var models = _repo.Read().Where(x => x.SupplierID == supplierID).OrderByDescending(s => s.Date);
            var viewModels = models.ToList().Select(s => _mapper.MapToViewModel(s));

            return Json(viewModels.ToDataSourceResult(request));
        }
    }
}

OfficeGroceries.Admin/Controllers/Settings/ProformaApproverGridController.cs
using System.Linq;
using System.Web.Mvc;
using NuIngredient.Models;

namespace NuIngredient.Controllers
{
    [Authorize(Roles = "NI-User")]
    public class ProformaApproverGridController : GridController<ProformaApprover, ProformaApproverGridViewModel>
    {
        public ProformaApproverGridController()
            :base(new ProformaApproverRepository(), new ProformaApproverGridMapper())
        {

        }
        
        public JsonResult DropDown()
        {
            var models = _repo.Read()
                .Select(u => new SelectItemViewModel()
                {
                    ID = u.ID.ToString(),
                    Name = u.Name
                })
                .ToList();

            return Json(models, JsonRequestBehavior.AllowGet);
        }
        
    }
}

OfficeGroceries.Admin/Controllers/Settings/SettingsController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using NuIngredient.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System.Web.Routing;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.IO;

namespace NuIngredient.Controllers
{
    [Authorize(Roles = "NI-User")]
    public class SettingsController : BaseController
    {
        CompanyRepository _repo = new CompanyRepository();
        CompanyMapper _mapper = new CompanyMapper();
        
        // GET: Settings
        public ActionResult Index()
        {            
            return View();
        }

        public ActionResult _Suppliers()
        {
            return PartialView();
        }

        public ActionResult _ProductCategories()
        {
            return PartialView();
        }

        public ActionResult _FruitProductCategories()
        {
            return PartialView();
        }

        public ActionResult _MilkProductCategories()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult _OverallSetting()
        {
            var model = new SnapDbContext().Settings.First();
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult _OverallSetting(Setting viewModel)
        {
            using (var db = new SnapDbContext())
            {
                var model = db.Settings.First();

                model.MilkSupplierCenterEmail = viewModel.MilkSupplierCenterEmail;
                model.FruitSupplierCenterEmail = viewModel.FruitSupplierCenterEmail;
                model.DryGoodsSupplierCenterEmail = viewModel.DryGoodsSupplierCenterEmail;
                model.FeedbackCenterEmail = viewModel.FeedbackCenterEmail;

                db.SaveChanges();

                ViewBag.Saved = true;

                return PartialView(model);
            }
        }
        
        [HttpGet]
        public ActionResult _FreezeSetting()
        {
            var model = new SnapDbContext().Settings.First();
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult _FreezeSetting(Setting viewModel)
        {
            using (var db = new SnapDbContext())
            {
                var model = db.Settings.First();

                model.IsFreezeActivated = viewModel.IsFreezeActivated;
                model.FreezeStartDate = viewModel.FreezeStartDate;
                model.FreezeEndDate = viewModel.FreezeEndDate;
                model.FreezeMessage = viewModel.FreezeMessage;

                db.SaveChanges();

                ViewBag.Saved = true;

                return PartialView(model);
            }
        }

        public ActionResult _Holidays()
        {
            return PartialView();
        }

        public ActionResult _Tags()
        {
            return PartialView();
        }
        
        public ActionResult _ProformaApprovers()
        {
            return PartialView();
        }

    }
}

OfficeGroceries.Admin/Controllers/Settings/TagGridController.cs
using System.Linq;
using System.Web.Mvc;
using NuIngredient.Models;

namespace NuIngredient.Controllers
{
    [Authorize(Roles = "NI-User")]
    public class TagGridController : GridController<Tag, TagGridViewModel>
    {
        public TagGridController()
            :base(new TagRepository(), new TagGridMapper())
        {

        }

        public JsonResult DropDownTags()
        {
            var result = _repo.Read()
                .OrderBy(t => t.Name)
                .ToList()
                .Select(t => _mapper.MapToViewModel(t));
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

OfficeGroceries.Admin/Controllers/Suppliers/IssueEmailGridController.cs
using System.Linq;
using System.Web.Mvc;
using NuIngredient.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System;

namespace NuIngredient.Controllers
{
    [Authorize]
    public class IssueEmailGridController : GridController<IssueEmail, IssueEmailGridViewModel>
    {
        public IssueEmailGridController()
            : base(new IssueEmailRepository(), new IssueEmailGridMapper())
        {

        }

        [HttpPost]
        public JsonResult Read([DataSourceRequest] DataSourceRequest request, Guid? supplierID, Guid? companyID)
        {
            var models = _repo.Read().AsQueryable();
            
            if (supplierID.HasValue)
            {
                models = models.Where(x => x.SupplierID == supplierID.Value);
            }
            
            if (companyID != Guid.Empty)
            {
                models = models.Where(x => x.CompanyID == companyID.Value);
            }
            
            var viewModels = models
                .OrderBy(x => x.Subject)
                .ToList()
                .Select(s => _mapper.MapToViewModel(s));

            return Json(viewModels.ToDataSourceResult(request));
        }
    }
    
}

OfficeGroceries.Admin/Controllers/Suppliers/SupplierDepotGridController.cs
using System.Linq;
using System.Web.Mvc;
using NuIngredient.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System;

namespace NuIngredient.Controllers
{
    [Authorize]
    public class SupplierDepotGridController : GridController<SupplierDepot, SupplierDepotGridViewModel>
    {
        public SupplierDepotGridController()
            : base(new SupplierDepotRepository(), new SupplierDepotGridMapper())
        {

        }

        [HttpPost]
        public JsonResult Read([DataSourceRequest] DataSourceRequest request, Guid supplierID)
        {
            var models = _repo.Read().Where(x => x.SupplierID == supplierID);
            var viewModels = models
                .OrderBy(x => x.Name)
                .ToList()
                .Select(s => _mapper.MapToViewModel(s));

            return Json(viewModels.ToDataSourceResult(request));
        }

        public JsonResult DropDown(Guid supplierID)
        {
            var models = _repo.Read()
                .Where(x => x.SupplierID == supplierID)
                .Select(x => new
                {
                    ID = x.ID,
                    Name = x.Name,
                    Email = x.Email
                })
                .ToList()
                .Select(x => new
                {
                    ID = x.ID.ToString(),
                    Name = $"{x.Name} ({x.Email})"
                })
                .Select(x => new SelectItemViewModel
                {
                    ID = x.ID,
                    Name = x.Name.Length > 50 ? x.Name.Substring(0, 50) + "..." : x.Name
                });

            return Json(models, JsonRequestBehavior.AllowGet);
        }

        
    }
    
}

OfficeGroceries.Admin/Controllers/Suppliers/SupplierFruitProductCodeGridController.cs
using System.Linq;
using System.Web.Mvc;
using NuIngredient.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System;
using System.Data.Entity;

namespace NuIngredient.Controllers
{
    [Authorize]
    public class SupplierFruitProductCodeGridController : GridController<SupplierFruitProductCode, SupplierFruitProductCodeGridViewModel>
    {
        public SupplierFruitProductCodeGridController()
            : base(new SupplierFruitProductCodeRepository(), new SupplierFruitProductCodeGridMapper())
        {

        }

        [HttpPost]
        public JsonResult Read([DataSourceRequest] DataSourceRequest request, Guid? supplierID, Guid? productID)
        {
            var query = _repo.Read().AsQueryable();

            if (supplierID != null)
            {
                query = query.Where(x => x.SupplierID == supplierID);
            }
            
            if (productID != null)
            {
                query = query.Where(x => x.FruitProductID == productID);
            }
            
            var viewModels = query
                .Include(x => x.FruitProduct)
                .Include(x => x.Supplier)
                .OrderBy(x => x.Code)
                .ToList()
                .Select(s => _mapper.MapToViewModel(s));

            return Json(viewModels.ToDataSourceResult(request));
        }

    }
    
}

OfficeGroceries.Admin/Controllers/Suppliers/SupplierOpenDayGridController.cs
using System.Linq;
using System.Web.Mvc;
using NuIngredient.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System;

namespace NuIngredient.Controllers
{
    [Authorize(Roles = "NI-User")]
    public class SupplierOpenDayGridController : GridController<SupplierOpenDay, SupplierOpenDayGridViewModel>
    {
        public SupplierOpenDayGridController()
            :base(new SupplierOpenDayRepository(), new SupplierOpenDayGridMapper())
        {

        }

        [HttpPost]
        public JsonResult Read([DataSourceRequest] DataSourceRequest request, Guid supplierID)
        {
            var models = _repo.Read().Where(x => x.SupplierID == supplierID);
            var viewModels = models.ToList().Select(s => _mapper.MapToViewModel(s));

            return Json(viewModels.ToDataSourceResult(request));
        }
    }
}

OfficeGroceries.Admin/Views/Settings/Business.cshtml
@model NuIngredient.Models.CompanyViewModel
@{
    ViewBag.Title = "Business";
}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            @if (ViewBag.SuccessMessage != null)
            {
                <div class="alert alert-success">
                    @ViewBag.SuccessMessage
                </div>
            }
            @if (ViewBag.ErrorMessage != null)
            {
                <div class="alert alert-danger">
                    <strong>Error:</strong> @ViewBag.ErrorMessage
                </div>
            }
        </div>
        <div class="col-sm-12">
            <h1>Your Business Details</h1>
            <hr />
        </div>
        @using (Html.BeginForm("Business", "Settings", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="col-sm-6">            
                @Html.AntiForgeryToken()
                @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })*@
                @Html.HiddenFor(model => model.ID)                
                <input type="hidden" id="LogoImageURL" name="LogoImageURL" value="@Model.LogoImageURL" />
               
                <table style="width:100%">
                    <tr>
                        <td style="width:140px;"><label>Business Name:</label></td>
                        <td>@Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })</td>
                    </tr>
                    <tr>
                        <td><label>Motto:</label></td>
                        <td>@Html.TextBoxFor(model => model.Motto, new { @class = "form-control" })</td>
                    </tr>
                    <tr>
                        <td><label>Address Line 1:</label></td>
                        <td>@Html.TextBoxFor(model => model.Address1, new { @class = "form-control" })</td>
                    </tr>
                    <tr>
                        <td><label>Address Line 2:</label></td>
                        <td>@Html.TextBoxFor(model => model.Address2, new { @class = "form-control" })</td>
                    </tr>
                    <tr>
                        <td><label>Address Line 3:</label></td>
                        <td>@Html.TextBoxFor(model => model.Address3, new { @class = "form-control" })</td>
                    </tr>
                    <tr>
                        <td><label>Town:</label></td>
                        <td>@Html.TextBoxFor(model => model.Town, new { @class = "form-control" })</td>
                    </tr>
                    <tr>
                        <td><label>Country:</label></td>
                        <td>@Html.TextBoxFor(model => model.Country, new { @class = "form-control" })</td>
                    </tr>
                    <tr>
                        <td><label>Postcode:</label></td>
                        <td>@Html.TextBoxFor(model => model.Postcode, new { @class = "form-control" })</td>
                    </tr>
                    <tr>
                        <td><label>Telephone:</label></td>
                        <td>@Html.TextBoxFor(model => model.Telephone, new { @class = "form-control" })</td>
                    </tr>
                    <tr>
                        <td><label>Mobile:</label></td>
                        <td>@Html.TextBoxFor(model => model.Mobile, new { @class = "form-control" })</td>
                    </tr>
                    <tr>
                        <td><label>Email:</label></td>
                        <td>@Html.TextBoxFor(model => model.Email, new { @class = "form-control" })</td>
                    </tr>
                    <tr>
                        <td><label>Website:</label></td>
                        <td>@Html.TextBoxFor(model => model.Website, new { @class = "form-control" })</td>
                    </tr>
                    <tr>
                        <td><label>VAT Number:</label></td>
                        <td>@Html.TextBoxFor(model => model.VatNumber, new { @class = "form-control" })</td>
                    </tr>
                    <tr>
                        <td><label>Default VAT Rate %:</label></td>
                        <td>@Html.Kendo().NumericTextBoxFor(model => model.DefaultVatRate).Decimals(2)</td>
                    </tr>
                    <tr>
                        <td><label>Default Currency:</label></td>
                        <td>
                            @(Html.Kendo().DropDownListFor(model => model.DefaultCurrencyID)
                                .DataTextField("Name").DataValueField("ID")
                                .DataSource(source =>
                                {
                                    source.Read(read => { read.Action("DropDownCurrencies", "Dropdowns"); });
                                })
                                .Value(Model.DefaultCurrencyID.ToString())
                                .AutoBind(true)
                            )
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                    </tr>
                </table>                    
            </div>
            <div class="col-sm-6">
                <label>Company Logo:</label><br />
                @if (Model.LogoImageURL != null)
                {
                    <a id="productImage_link" class="fancybox-media" target="_blank" href="@Model.LogoImageURL" title="@Model.Name">
                        <img id="productImage" src="@Model.LogoImageURL" style="max-height:100px; max-width:500px" />
                    </a>
                    <br />
                    <br />
                    <input type="submit" name="Remove" value="Remove Logo" />
                }
                else
                {
                    <label>Upload Company Logo:</label><br />
                    <input id="logoImage" type="file" name="logoImage" accept="image/*" />
                    <span style="font-size:x-small">Max 5Mbs</span>
                    <hr />
                    <input type="submit" value="Save Business Details" class="btn btn-success" />
                }
            </div>
            <div class="col-sm-12">
                <hr />
                <input type="submit" value="Save Business Details" class="btn btn-success" />
            </div>
        }

        <div class="col-sm-12">
            <hr />
            <h2>Delivery Addresses</h2>
            <div>
                <a class="btn btn-info btn-sm" onclick="$('#GridAddresses').data('kendoGrid').addRow();" style="margin-bottom:5px;"><span class="glyphicon glyphicon-book"></span>&nbsp;&nbsp;Add New Address</a>
            </div>
            @(Html.Kendo().Grid<NuIngredient.Models.CompanyAddressViewModel>()
                .Name("GridAddresses")
                .Pageable(p => p.PageSizes(new[] { 25, 50, 100 }).Messages(m => m.Display("{0} - {1} of {2} Addresses").Empty("No Addresses Added")))
                .Columns(columns =>
                {
                    columns.Bound(t => t.Name).Title("Business Name");
                    columns.Bound(t => t.Address1).Title("Address 1");
                    columns.Bound(t => t.Address2).Title("Address 2");
                    columns.Bound(t => t.Address3).Title("Address 3");
                    columns.Bound(t => t.Town).Title("Town");
                    columns.Bound(t => t.Postcode).Title("Postcode");
                    columns.Bound(t => t.Country).Title("Country");
                    columns.Bound(t => t.Telephone).Title("Telephone");
                    columns.Bound(t => t.Mobile).Title("Mobile");
                    columns.Bound(t => t.Email).Title("Email");
                    columns.Command(command =>
                    {
                        command.Edit().Text("<span class='glyphicon glyphicon-edit glyphicon-btn'/>").UpdateText("<span class='glyphicon glyphicon-ok glyphicon-btn'/>").CancelText("<span class='glyphicon glyphicon-remove glyphicon-btn'/>");
                        command.Destroy().Text("<span class='glyphicon glyphicon-trash glyphicon-btn'/>");
                    }
                    ).Width("90px");
                })
                .Editable(editable => editable.Mode(GridEditMode.InLine).ConfirmDelete("Are you sure you want to delete this address?"))
                .Sortable()
                .DataSource(dataSource => dataSource
                    .Ajax()
                    //.Sort(sort => sort.Add("FirstName").Ascending()) // <-- initial sort expression
                    .Model(model =>
                    {
                        model.Id(t => t.ID);
                        model.Field(t => t.ID).Editable(false);
                        model.Field(t => t.CompanyID).Editable(false).DefaultValue(Model.ID);
                    })
                    .Create(create => create.Action("Create", "CompanyAddresses", new { companyID = Model.ID }))
                    .Read(read => read.Action("Read", "CompanyAddresses", new { companyID = Model.ID }))
                    .Update(update => update.Action("Update", "CompanyAddresses", new { companyID = Model.ID }))
                    .Destroy(destroy => destroy.Action("Destroy", "CompanyAddresses", new { companyID = Model.ID }))
                )
                .Events(events => events.DataBound("KendoGridDatabound"))
            )
        </div>
    </div>
</div>

<style>
    th, td {
        padding: 2px;       
    }

    .form-control{
        max-width:none;
        width:90%;
    }
</style>

OfficeGroceries.Admin/Views/Settings/Index.cshtml
@using NuIngredient.Models

@{
    ViewBag.Title = "Admin";
}

<script>
    $(function () {
        loadInitialView();

        // Hook up the nav pill buttons.
        $(".nav-pills li").click(function (e) {
            e.preventDefault();

            // Update the highlighting of the pills.
            $(".nav-pills li.active").removeClass("active");
            $(this).addClass("active");

            // Call the href of the pill as a child action.
            loadFromPillButton($(this));
        })
    });

    // Loads the partial view for the first nav pill button and sets the button to active.
    function loadInitialView() {
        var $button = $(".nav-pills li:first-child");
        $button.addClass("active");
        loadFromPillButton($button);
    }

    // Loads content from the anchor tag of a pill button.
    function loadFromPillButton($a) {
        var url = $a.children("a").attr("href");
        $("#divContent").load(url)
    }
</script>

<div class="container" style="margin-top: 30px;">
    <div class="row">
        <div class="col-sm-2">
            <div class="panel panel-default">
                <div class="panle-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <ul class="nav nav-pills nav-stacked" style="margin-top: 5px;">
                                <li><a href="@Url.Action("_OverallSetting", "Settings")">Overall Settings</a></li>
                                <li><a href="@Url.Action("_Holidays", "Settings")">Holidays</a></li>
                                <li><a href="@Url.Action("_Tags", "Settings")">Tags</a></li>
                                <li><a href="@Url.Action("_ProformaApprovers", "Settings")">Proforma Approvers</a></li>
                                <li><a href="@Url.Action("_FreezeSetting", "Settings")">Freeze Setting</a></li>
                                <li>@*<a href='@Url.Action("_Suppliers", "Settings")'>Suppliers</a>*@</li>
                                @*<li><a href='@Url.Action("_ProductCategories", "Settings")'>Dry Goods Categories</a></li>
                                <li><a href='@Url.Action("_FruitProductCategories", "Settings")'>Fruit Categories</a></li>
                                <li><a href='@Url.Action("_MilkProductCategories", "Settings")'>Milk Categories</a></li>*@
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-10">
            <hr class="visible-xs" />
            <div id="divContent" style="margin-left: 20px;"></div>
        </div>
    </div>
</div>

  <!-- Modal -->
<div class="modal fade" id="Modal" role="dialog" style="z-index:2000">
    <div class="modal-dialog" style="width:400px;">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title" style="text-align:center;"></h4>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>