OfficeGroceries.Admin/Controllers/CMS/PageSettingsController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using NuIngredient.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System.Web.Routing;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.IO;
using Kendo.Mvc;
using System.ComponentModel;

namespace NuIngredient.Controllers
{
    [Authorize(Roles = "NI-User")]
    public class PageSettingsController : GridController<PageSetting, PageSettingViewModel>
    {

        public PageSettingsController()
            : base(new PageSettingRepository(), new PageSettingMapper())
        {

        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult _New()
        {
            return PartialView(new PageSettingViewModel());
        }

        [HttpPost]
        public ActionResult _New(PageSettingViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return PartialView(viewModel);

            var model = _mapper.MapToModel(viewModel);
            _repo.Create(model);

            return Json(new { ID = model.ID });
        }

        [HttpGet]
        public ActionResult _Edit(Guid id)
        {
            var model = _repo.Find(id);
            var viewModel = _mapper.MapToViewModel(model);

            return PartialView(viewModel);
        }

        [HttpPost]
        public ActionResult _Edit(PageSettingViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var model = _repo.Find(Guid.Parse(viewModel.ID));

                _mapper.MapToModel(viewModel, model);

                _repo.Update(model);

                ViewBag.Saved = true;
            }

            return PartialView(viewModel);
        }
    }
}

OfficeGroceries.Admin/Views/PageSettings/Index.cshtml
@{
    ViewBag.Title = "Page Settings";
}
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <h1>@ViewBag.Title</h1>
        </div>
        <div class="col-xs-12">
            <hr />
        </div>
        <div id="divPager" class="col-sm-12">
            <div class="form-group" role="group" aria-label="...">
                <button class="btn btn-sm btn-default" onclick="Refresh();"><span class="glyphicon glyphicon-refresh"></span>&nbsp; Refresh</button>&nbsp;
                @*<button class="btn btn-sm btn-warning" onclick="NewPage();"><span class="glyphicon glyphicon-plus-sign"></span>&nbsp; New Page</button>*@&nbsp;
            </div>
        </div>
        <div class="col-xs-12">
            @(Html.Kendo().Grid<NuIngredient.Models.PageSettingGridViewModel>()
                .Name("GridPages")
                .Pageable(p => p.PageSizes(new[] { 10, 20, 50 }).Messages(m => m.Display("{0} - {1} of {2} Pages").Empty("No Pages Found")))
                .Columns(columns =>
                {
                columns.Bound(p => p.ID).Hidden();
                columns.Bound(p => p.Label);
                columns.Bound(p => p.FilePath);
                //columns.Bound(p => p.Active).Title("Status").ClientTemplate("#if(Active == true) {# Active #} else {# Inactive #}#").Width("1%");
                columns.Template(@<text></text>).ClientTemplate("<a title='Edit' href='\\#' onclick='EditPage(\"#=ID#\"); return false;'><span class='glyphicon glyphicon-edit glyphicon-btn'/></a>").Width("1%");
                    //columns.Command(commands =>
                    //{
                    //    commands.Destroy().Text("<span class='glyphicon glyphicon-btn glyphicon-trash' />");
                    //}).Width("1%");
                })
                //.Sortable()
                .DataSource(dataSource => dataSource
                    .Ajax()
                    .Model(model =>
                    {
                        model.Id(t => t.ID);
                    })
                    .Read(read => read.Action("Read", "PageSettingGrid")).PageSize(50)
                    .Destroy(destroy => destroy.Action("Destroy", "PageSettingGrid"))
                )
                .Events(events => events.DataBound("KendoGridDatabound"))
            )
        </div>
    </div>
</div>

<a id="Button_Close_Content" class="btn btn-background" onclick="HideViews()" style="z-index:1105; display:none;"></a>

<div id="SlideContent_Edit" class="panel panel-default" style="z-index: 1120; position: fixed; overflow-y:scroll; margin: 0; top: 0; bottom:0; right: 0%; min-height: 100%; width: 0; max-width: 800px; display: none;">
    <div class="panel-body" style="margin-top: 10px;">
        <div id="Edit_Body"></div>
    </div>
</div>

<script>
    function Refresh() {
        $('#GridPages').data('kendoGrid').dataSource.read();
    }

    function NewPage() {
        var url = '@Url.Action("_New", "PageSettings")';
        $("#Edit_Body").load(url);

        $("#SlideContent_Edit").animate({ width: '90%' }, { queue: false, duration: 300 });
        $("#SlideContent_Edit").css("display", "block");
        $("#Button_Close_Content").css("display", "block");
    }

    function CreatedPage(id) {
        Refresh();
        var url = '@Url.Action("_Edit", "PageSettings")' + '/' + id;
        $("#Edit_Body").load(url);
    }

    function EditPage(id) {
        var url = '@Url.Action("_Edit", "PageSettings")' + '/' + id;
        $("#Edit_Body").load(url);

        $("#SlideContent_Edit").animate({ width: '90%' }, { queue: false, duration: 300 });
        $("#SlideContent_Edit").css("display", "block");
        $("#Button_Close_Content").css("display", "block");
    }

    function TemplateTarget(messageTargets) {
        var template = "";
        for (var i = 0; i < messageTargets.length; i++) {
            template += "<span class='label label-primary' style='background-color: " + messageTargets[i].Colour + "'>" + messageTargets[i].Name + "</span> ";
        }
        return template;
    }
</script>

OfficeGroceries.Admin/Views/PageSettings/_Edit.cshtml
@model NuIngredient.Models.PageSettingViewModel

<div class="container" id="divEditPage">

    @using (Ajax.BeginForm("_Edit", "PageSettings", null, new AjaxOptions { UpdateTargetId = "divEditPage", OnBegin = "AjaxBegin", OnComplete = "AjaxComplete" }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        //@Html.ValidationSummary(false, "", new { @class = "alert alert-danger" })
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.Active)

        <div class="row">
            <div class="col-xs-9">
                <h2>Edit Page</h2>
            </div>
            <div class="col-xs-3">
                <br />
                <br />
                <a class="btn btn-sm btn-default" onclick="HideViews(); return false;" style="float:right;"><span class="glyphicon glyphicon-remove"></span>&nbsp;Close</a>
            </div>
        </div>

        <div class="row form-table">
            <div class="col-sm-12">
                <hr />
                <table class="table-responsive">
                    <tr>
                        <td style="width:120px;"><label>Label:</label></td>
                        <td>
                            @Html.TextBoxFor(model => model.Label, new { @class = "form-control", @placeholder = "Enter Label", @style = "max-width: none;", @readonly = "readonly" })
                            @Html.ValidationMessageFor(model => model.Label, "", new { @class = "text-danger" })
                        </td>
                    </tr>
                    <tr>
                        <td><label>File Path:</label></td>
                        <td>
                            @Html.TextBoxFor(model => model.FilePath, new { @class = "form-control", @placeholder = "Enter File Path", @style = "max-width: none;" })
                            @Html.ValidationMessageFor(model => model.FilePath, "", new { @class = "text-danger" })
                        </td>
                    </tr>
                    <tr>
                        <td><label>Meta Title:</label></td>
                        <td>
                            @Html.TextBoxFor(model => model.MetaTitle, new { @class = "form-control", @placeholder = "Enter Meta Title", @style="max-width: none;" })
                            @Html.ValidationMessageFor(model => model.MetaTitle, "", new { @class = "text-danger" })
                        </td>
                    </tr>
                    <tr>
                        <td><label>Meta Keyword:</label></td>
                        <td>
                            
                            @Html.TextBoxFor(model => model.MetaKeyword, new { @class = "form-control", @placeholder = "Enter Meta Keyword", @style = "max-width: none;" })
                            @Html.ValidationMessageFor(model => model.MetaKeyword, "", new { @class = "text-danger" })


                        </td>
                    </tr>
                    <tr>
                        <td><label>Meta Description:</label></td>
                        <td>

                            @Html.TextBoxFor(model => model.MetaDescription, new { @class = "form-control", @placeholder = "Enter Meta Description", @style = "max-width: none;" })
                            @Html.ValidationMessageFor(model => model.MetaDescription, "", new { @class = "text-danger" })


                        </td>
                    </tr>
                    @*<tr>
                        <td><label>Active:</label></td>
                        <td>
                            @Html.Kendo().CheckBoxFor(model => model.Active)
                            @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                        </td>
                    </tr>*@
                </table>
            </div>
            
            <div class="col-sm-12">

            </div>

            <div class="col-sm-12">
                <br /><br />
                <input type="submit" value="Save" class="btn btn-inverse">
                @if (ViewBag.Saved != null)
                {
                    <br />
                    <label class="l_Saved"><strong>Details Saved!</strong></label>
                }
            </div>
            <div class="col-sm-12">
                <hr />
            </div>
        </div>
    }

</div>

OfficeGroceries.Admin/Views/PageSettings/_New.cshtml
@model NuIngredient.Models.PageSettingViewModel

<div class="container" id="divNewPage">

    @using (Ajax.BeginForm("_New", "PageSettings", null, new AjaxOptions { UpdateTargetId = "divNewPage", OnSuccess = "OnSuccess", OnBegin = "AjaxBegin", OnComplete = "AjaxComplete" }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        //@Html.ValidationSummary(false, "", new { @class = "alert alert-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="row">
            <div class="col-xs-9">
                <h2>New Message</h2>
            </div>
            <div class="col-xs-3">
                <br />
                <br />
                <a class="btn btn-sm btn-default" onclick="HideViews(); return false;" style="float:right;"><span class="glyphicon glyphicon-remove"></span>&nbsp;Close</a>
            </div>
        </div>

        <div class="row form-table">
            <div class="col-sm-12">
                <hr />
                <table>
                    <tr>
                        <td style="width:120px;"><label>Label:</label></td>
                        <td>
                            @Html.TextBoxFor(model => model.Label, new { @class = "form-control", @placeholder = "Enter Label", @style = "max-width: none;" })
                            @Html.ValidationMessageFor(model => model.Label, "", new { @class = "text-danger" })
                        </td>
                    </tr>
                    <tr>
                        <td><label>File Path:</label></td>
                        <td>
                            @Html.TextBoxFor(model => model.FilePath, new { @class = "form-control", @placeholder = "Enter File Path", @style = "max-width: none;" })
                            @Html.ValidationMessageFor(model => model.FilePath, "", new { @class = "text-danger" })
                        </td>
                    </tr>
                    <tr>
                        <td><label>Meta Title:</label></td>
                        <td>
                            @Html.TextBoxFor(model => model.MetaTitle, new { @class = "form-control", @placeholder = "Enter Meta Title", @style = "max-width: none;" })
                            @Html.ValidationMessageFor(model => model.MetaTitle, "", new { @class = "text-danger" })
                        </td>
                    </tr>
                    <tr>
                        <td><label>Meta Keyword:</label></td>
                        <td>

                            @(Html.Kendo().EditorFor(model => model.MetaKeyword)
                                          .HtmlAttributes(new { @class = "form-control", @placeholder = "Enter Meta Keyword here", @style = "max-width:none; margin-bottom:10px; heigh:350px;" })
                                          .Encode(false)
                                          .Tools(tools => tools.Clear())
                                          .Resizable()
                            )
                            @Html.ValidationMessageFor(model => model.MetaKeyword, "", new { @class = "text-danger" })


                        </td>
                    </tr>
                    <tr>
                        <td><label>Meta Description:</label></td>
                        <td>

                            @(Html.Kendo().EditorFor(model => model.MetaDescription)
                                          .HtmlAttributes(new { @class = "form-control", @placeholder = "Enter Meta Description here", @style = "max-width:none; margin-bottom:10px; heigh:350px;" })
                                          .Encode(false)
                                          .Tools(tools => tools.Clear())
                                          .Resizable()
                            )
                            @Html.ValidationMessageFor(model => model.MetaDescription, "", new { @class = "text-danger" })


                        </td>
                    </tr>
                    <tr>
                        <td><label>Active:</label></td>
                        <td>
                            @Html.Kendo().CheckBoxFor(model => model.Active)
                            @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                        </td>
                    </tr>
                </table>
            </div>
            
            <div class="col-sm-12">

            </div>

            <div class="col-sm-12">
                <br /><br />
                <input type="submit" value="Save" class="btn btn-inverse">
            </div>
            <div class="col-sm-12">
                <hr />
            </div>
        </div>
    }

    <script>
        function OnSuccess(response) {
            //Call function from Index view
            if (response["ID"] != null) {
                CreatedPage(response["ID"]);
            }
        }
    </script>
</div>