OfficeGroceries.Admin/Controllers/FruitProducts/FruitProductManagementController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using NuIngredient.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System.Web.Routing;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.IO;
using Kendo.Mvc;

namespace NuIngredient.Controllers
{
    [Authorize(Roles = "NI-User")]
    public class FruitProductManagementController : EntityController<FruitProduct, EditFruitProductViewModel>
    {

        public FruitProductManagementController()
            : base(new FruitProductRepository(), new EditFruitProductModelMapper())
        {

        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult _New()
        {
            var model = new FruitProduct();
            var viewModel = _mapper.MapToViewModel(model);
            return PartialView(viewModel);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult _New(EditFruitProductViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return PartialView(viewModel);
            }

            var model = _mapper.MapToModel(viewModel);
            _repo.Create(model);

            viewModel.ID = model.ID.ToString();

            UpdateCategories(viewModel);

            return Json(new { ID = model.ID });
        }

        [HttpGet]
        public ActionResult _Edit(Guid id)
        {
            var viewModel = _mapper.MapToViewModel(_repo.Find(id));
            return PartialView(viewModel);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult _Edit(EditFruitProductViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return PartialView(viewModel);
            }

            var model = _repo.Find(Guid.Parse(viewModel.ID));

            var isPriceChanged = model.Price != viewModel.Price || model.VAT != viewModel.VAT;

            _mapper.MapToModel(viewModel, model);
            _repo.Update(model);

            if (isPriceChanged)
            {
                var helper = RefreshFruitPriceHelper.New();
                helper.RefreshOrderPrice(model.ID);
            }

            UpdateCategories(viewModel);

            viewModel.ImageURL = model.ImageURL;

            ViewBag.Saved = true;

            return PartialView(viewModel);
        }

        public ActionResult UploadProductImage(HttpPostedFileBase uploadedProductImage, string id)
        {
            const string relativePath = "/Images/";

            if (uploadedProductImage == null) return Json(new { status = "error", message = "No Image uploaded." }, "text/plain");
            if (!uploadedProductImage.ContentType.Contains("image")) return Json(new { status = "error", message = "Uploaded file is not an Image." }, "text/plain");
            if (uploadedProductImage.ContentLength > 10 * 1024 * 1024) return Json(new { status = "error", message = "Uploaded file is too big." }, "text/plain");


            var model = _repo.Find(Guid.Parse(id));

            //Save file on Server
            string loc = SaveFile(uploadedProductImage, relativePath);

            //Update the image URL of the product    
            model.ImageURL = loc;
            _repo.Update(model, new string[] { "ImageURL" });

            //return the image loc. Javascript updates the image in view
            return Json(new { status = "success", id = id }, "text/plain");

        }

        public ActionResult RemoveProductImage(string id)
        {
            var model = _repo.Find(Guid.Parse(id));
            model.ImageURL = null;
            _repo.Update(model, new string[] { "ImageURL" });

            return Json(new { status = "success", id = id }, "text/plain");
        }


        private void UpdateCategories(EditFruitProductViewModel viewModel)
        {
            var model = _repo.Read()
                             .Where(x => x.ID.ToString() == viewModel.ID)
                             .Include(x => x.Categories)
                             .FirstOrDefault();

            var oldList = model != null ? model.Categories.Select(x => x.CategoryID.ToString()) : new List<string>();
            var newList = viewModel.CategoryIDs ?? new List<string>();

            var listToDelete = oldList.Except(newList).ToList();
            var listToAdd = newList.Except(oldList).ToList();

            var repo = new FruitCategoryLinkRepository();
            foreach (var id in listToDelete)
            {
                repo.Delete(repo.Read().Where(x => x.CategoryID.ToString() == id && x.FruitProductID.ToString() == viewModel.ID));
            }
            foreach (var id in listToAdd)
            {
                repo.Create(new FruitCategoryLink() { CategoryID = Guid.Parse(id), FruitProductID = Guid.Parse(viewModel.ID) });
            }
        }

    }
}

OfficeGroceries.Admin/Views/FruitProductManagement/Deleted.cshtml
@{
    ViewBag.Title = "Deleted Products";
}

<div class="row">
    <div class="col-sm-9">
        <h2>Deleted Products</h2>        
    </div>
    <div class="col-sm-3">
        <br />
        <a class="btn btn-default" style="float:right;" href="@Url.Action("Index", "Products")"><span class="glyphicon glyphicon-arrow-left"></span>&nbsp;Back To Products</a>
    </div>
    <div class="col-sm-12">
        <hr />
        <div class="form-group" role="group" aria-label="...">
            <a class="btn btn-sm btn-default" onclick="RefreshProducts(); return false;"><span class="glyphicon glyphicon-refresh"></span>&nbsp; Refresh</a>
            <a class="btn btn-sm btn-danger" onclick="ClearProducts(); return false;"><span class="glyphicon glyphicon-fire"></span>&nbsp; Clear</a>
        </div>
    </div>
    <div class="col-sm-12">
        @(Html.Kendo().Grid<NuIngredient.Models.ProductGridViewModel>()
                .Name("GridProducts")
                .Pageable(p => p.PageSizes(new[] { 50, 100, 200 }).Messages(m => m.Display("{0} - {1} of {2} Products").Empty("No Deleted Products Found")))
                .Columns(columns =>
                {
                    columns.Bound(u => u.ID).ClientTemplate("<input type='checkbox' value='#=ID#' name='chk_grid'>").Width("1%").Hidden();
                    columns.Bound(u => u.ImageURL).Title("Image").ClientTemplate("<a class='fancybox-media' target='_blank' href='#=ImageURL#' title='#=ProductCode#'><img src='#=ImageURL#' style='width:100%; max-height:35px; max-width:35px;'></a>").Width("1%");
                    columns.Bound(u => u.ProductCode).Title("Product Code");
                    columns.Bound(u => u.Category).Title("Category");
                    columns.Bound(u => u.Description).Title("Description").ClientTemplate("#=Description#<div class='div-inline' style='float:right'>#if(IsKit){ #<span class='glyphicon glyphicon-th-large' title='Product Kit' style='margin-left:3px'/># }#"
                                                                 + "#if(IsService){ #<span class='glyphicon glyphicon-wrench' title='Service/Recurring'  style='margin-left:3px'/># }#</div>").Width("50%");
                    columns.Bound(u => u.VendorCode).Title("Vendor Code");
                    columns.Bound(u => u.Manufacturer).Title("Manufacturer");
                    columns.Bound(u => u.Unit).Title("Unit");
                    columns.Bound(u => u.Prices).Title("Prices").ClientTemplate("<div class='div-inline'>#=Prices#</div>").Sortable(false);
                    columns.Template(@<text></text>).ClientTemplate("<a title='Restore' href='\\#' onclick='RestoreProduct(\"#=ID#\"); return false;'><span class='glyphicon glyphicon-share-alt glyphicon-btn'/></a>").Width("1%");
                    columns.Command(command =>
                    {
                        command.Destroy().Text("<span class='glyphicon glyphicon-fire glyphicon-btn' title='Delete Permanently'/>");
                    }
                    ).Width("1%");
                })
                .Sortable()
                .DataSource(dataSource => dataSource
                    .Ajax()
                    .Model(model =>
                    {
                        model.Id(t => t.ID);                        
                    })
                    .Read(read => read.Action("Read", "ProductGrid").Data("GetSearchInfo")).PageSize(50)
                    .Destroy(destory => destory.Action("Destroy", "ProductGrid"))
                )
                .Events(events => events.DataBound("KendoGridDatabound"))
        )
    </div>
</div>

<script>

    function RefreshProducts() {
        var grid = $("#GridProducts").data("kendoGrid");
        grid.dataSource.read();
    }

    function GetSearchInfo() {
        return {
            filterText: "",
            category: "",
            del: true
        }
    }

    function RestoreProduct(id) {        
        $.ajax({ url: '@Url.Action("_RestoreDeletedProduct", "ProductGrid")', type: 'POST', data: { "ID": id }, dataType: "json", success: function (data) { RefreshProducts(); }  });      
    }

    function ClearProducts() {
        if (confirm('Permanently remove all deleted products?')) {
            $.ajax({ url: '@Url.Action("_ClearDeletedProducts", "ProductGrid")', type: 'POST', data: {}, dataType: "json", success: function (data) { RefreshProducts(); } });
        }
    }

</script>

OfficeGroceries.Admin/Views/FruitProductManagement/Index.cshtml
@{
    ViewBag.Title = "Fruit Management";
}

<div class="container">
    <div class="row">
        <div class="col-xs-6">
            <h1>@ViewBag.Title</h1>
        </div>
        <div class="col-xs-6">
            <br />
        </div>
        <div class="col-xs-12">
            <br />
        </div>
        <div class="col-xs-6">
            <a class="btn btn-primary" onclick="NewFruit(); return false;"><span class="fa fa-cube"></span>&nbsp;&nbsp;New Fruit</a>
        </div>
        <div class="col-xs-2">
            @(Html.Kendo().DropDownList()
                          .Name("DropDownCategories")
                          .OptionLabel("All Categories")
                          .DataTextField("Name")
                          .DataValueField("ID")
                          .DataSource(dataSource => dataSource.Read(read => read.Action("DropDownAllCategories", "FruitProductCategories")))
                          .Events(events => events.Change("Refresh"))
                          .HtmlAttributes(new { @style = "width: 100%;" })
            )
        </div>
        <div class="col-xs-4">
            <div class="input-group">
                @Html.TextBox("TB_FruitFilter", null, new { @class = "form-control", @style = "max-width:none;", @placeholder = "Search by Name or Description" })
                <span class="input-group-btn">
                    <a class="btn btn-default" onclick="Refresh(); return false;"><span class="glyphicon glyphicon-search"></span></a>
                </span>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <hr />
        </div>
        <div id="divPager" class="col-sm-12">
            <div class="form-group" role="group" aria-label="...">
                <button class="btn btn-sm btn-default" onclick="Refresh();"><span class="glyphicon glyphicon-refresh" ></span>&nbsp; Refresh</button>&nbsp;
                <div class="pull-right">
                    @(Html.Kendo().CheckBox().Label("Show Inactive").Name("ShowInactive").HtmlAttributes(new {onclick="Refresh();"}))
                </div>                 
            </div>
        </div>
        <div class="col-sm-12">
            @(Html.Kendo().Grid<NuIngredient.Models.FruitProductGridViewModel>()
                .Name("GridFruits")
                .Pageable(p => p.PageSizes(new[] { 50, 100, 200, 1000 }).Messages(m => m.Display("{0} - {1} of {2} Fruits").Empty("No Fruits Found")))
                .Columns(columns =>
                {
                    columns.Bound(u => u.ID).ClientTemplate("<input type='checkbox' value='#=ID#' name='chk_grid'>").Width("1%").Hidden();
                    columns.Bound(u => u.ImageURL).Title("Image").ClientTemplate("<a class='fancybox-media' target='_blank' href='#=ImageURL#' ><img src='#=ImageURL#' style='width:100%; max-height:50px; max-width:50px;'></a>").Width(70);
                    columns.Bound(u => u.Name).Width(200);
                    columns.Bound(u => u.CategoryName).Title("Category").HtmlAttributes(new {@style="white-space: pre-line;"}).Width(150);
                    columns.Bound(u => u.ShortDescription).Title("Description").Width(200);
                    columns.Bound(u => u.Unit).Title("Unit").Width(70);
                    //columns.Bound(u => u.Price).ClientTemplate("#=kendo.toString(Price, 'C')#");
                    columns.Bound(u => u.Prices).HtmlAttributes(new { @style = "white-space: pre;" }).Width(150);
                    columns.Bound(u => u.VAT).ClientTemplate("#=kendo.toString(VAT, 'p')#").Width(65);
                    columns.Bound(u => u.IsActive).Title("Active").ClientTemplate("<i class='glyphicon #if(IsActive){#glyphicon-check#}else{#glyphicon-unchecked#}#'></i>").HtmlAttributes(new { @style = "text-align:center", @title="Tick if the product is alive." }).Width(30);
                    columns.Bound(u => u.IsExclusive).Title("Exclusive").ClientTemplate("<i class='glyphicon #if(IsExclusive){#glyphicon-check#}else{#glyphicon-unchecked#}#'></i>").HtmlAttributes(new { @style = "text-align:center", @title= "Tick if the product shows to only the customers with customer prices." }).Width(30);
                    columns.Bound(u => u.IsProspectsVisible).Title("Prospects Visible").ClientTemplate("<i class='glyphicon #if(IsProspectsVisible){#glyphicon-check#}else{#glyphicon-unchecked#}#'></i>").HtmlAttributes(new { @style = "text-align:center", @title="Tick if the product shows to prospects." }).Width(30);
                    columns.Template(@<text></text>).ClientTemplate("<a title='Edit' href='\\#' onclick='EditFruit(\"#=ID#\"); return false;'><span class='glyphicon glyphicon-edit glyphicon-btn'/></a>").Width(50);
                    columns.Command(command =>
                    {
                        command.Destroy().Text("<span class='glyphicon glyphicon-trash glyphicon-btn'/>");
                    }
                    ).Width(50);

                })
                .Scrollable(scrollable => scrollable.Height(500).Enabled(true))
                .Editable(editable => editable.Mode(GridEditMode.InLine).ConfirmDelete("Are you sure you want to delete this product?"))
                //.Sortable()
                .DataSource(dataSource => dataSource
                    .Ajax()
                    .Model(model =>
                    {
                        model.Id(t => t.ID);
                    })
                    .Read(read => read.Action("Read", "FruitProductGrid").Data("GetSearchInfo")).PageSize(50)
                    .Destroy(destory => destory.Action("Destroy", "FruitProductGrid"))
                )
                .Events(events => events.DataBound("KendoGridDatabound"))
            )
        </div>
    </div>
</div>

<style>
    .div-inline {         
        overflow: hidden;
        white-space: nowrap;
        text-align:center;
        align-items:center;
    }
</style>

<a id="Button_Close_Content" class="btn btn-background" onclick="HideViews()" style="z-index:1105; display:none;"></a>

<div id="SlideContent_Edit" class="panel panel-default" style="z-index: 1120; position: fixed; overflow-y:scroll; margin: 0; top: 0; bottom:0; right: 0%; min-height: 100%; width: 0; max-width: 1300px; display: none;">
    <div class="panel-body" style="margin-top: 10px;">
        <div id="Edit_Body"></div>
    </div>
</div>

  <!-- Modal -->
<div class="modal fade" id="Modal" role="dialog" style="z-index:1200;">
    <div class="modal-dialog" style="width:400px;">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

<script>

    @if (!string.IsNullOrEmpty(ViewBag.ProductID))
    {
        <text>
        EditProduct('@ViewBag.ProductID');
        </text>
    }

    function Refresh() {
        var grid = $("#GridFruits").data("kendoGrid");
        grid.dataSource.read();
    }

    function GetSearchInfo() {
        return {
            filterText: $('#TB_FruitFilter').val(),
            categoryID: $('#DropDownCategories').val(),
            showInactive: $('#ShowInactive').is(':checked')
        }
    }

    $("#TB_FruitFilter").keyup(function (e) {
        if (e.keyCode == 13) {
            Refresh();
        }
    });


    //Below the following functions are used the show/hide the content panels.
    function NewFruit() {
        $("#Edit_Body").load("@Url.Action("_New", "FruitProductManagement")");

        $("#SlideContent_Edit").animate({ width: '90%' }, { queue: false, duration: 300 });
        $("#SlideContent_Edit").css("display", "block");
        $("#Button_Close_Content").css("display", "block");
    }

    function EditFruit(id) {
        var url = '@Url.Action("_Edit", "FruitProductManagement")' + '?ID=' + id;
        $("#Edit_Body").load(url);

        $("#SlideContent_Edit").animate({ width: '90%' }, { queue: false, duration: 300 });
        $("#SlideContent_Edit").css("display", "block");
        $("#Button_Close_Content").css("display", "block");
    }

    function CreatedFruit(id) {
        var url = '@Url.Action("_Edit", "FruitProductManagement")' + '?ID=' + id;
        $("#Edit_Body").load(url);
    }

    function HideViews() {
        $("#SlideContent_Edit").animate({ width: '0%' }, { queue: false, duration: 300 });
        setTimeout(function () {
            $("#SlideContent_Edit").css("display", "none");
            $("#Button_Close_Content").css("display", "none");
            Refresh();
        }, 300);
    }

    $(".k-grid[id='GridFruits'] table").kendoSortable({
        connectWith: ".k-grid[id='GridFruits'] table",
        filter: ">tbody >tr:not('.k-grid-edit-row')",
        disabled: ".no-drag", //do not allow transferring the no records row
        hint: $.noop,
        cursor: "move",
        placeholder: function (element) {
            return element.clone().addClass("k-state-hover").css("opacity", 0.65);
        },
        change: function (e) { //change event handler implementation may differ according to the scenario
            let categoryID = $('#DropDownCategories').val();
            if (categoryID == '') {
                Refresh();
                return alert("You can only sort when category selected");
            }

            try {
                var element = this.element.closest(".k-grid[id='GridFruits']");
                var grid = this.element.closest(".k-grid[id='GridFruits']").data("kendoGrid");
                var dataItem = null; grid.dataSource.getByUid(e.item.data("uid"));

                $('[id="GridFruits"]').each(function () {
                    if (dataItem == null)
                        dataItem = $(this).data('kendoGrid').dataSource.getByUid(e.item.data("uid"));
                });

                if (e.action == "receive" || e.action == "sort")
                    $.ajax({
                    url: '@Url.Action("_UpdateProductPositions", "FruitProductGrid")',
                        type: 'POST',
                        data: {
                            productID: dataItem.ID,
                            oldIndex: e.oldIndex,
                            newindex: e.newIndex,
                            categoryID: categoryID
                        },
                        dataType: "json",
                        success: function (data) { Refresh(); }
                });
            }
            catch (ex) { Refresh(); }
        },
        move: function(e) {
            console.log("move to index: " + this.indexOf(this.placeholder));
        }
    });
</script>

OfficeGroceries.Admin/Views/FruitProductManagement/_CustomerPricesTab.cshtml
@model NuIngredient.Models.EditFruitProductViewModel
    <br />
    <a class="btn btn-info btn-xs" onclick="$('#GridExclusivePrices').data('kendoGrid').addRow();" style="margin-bottom:5px;"><span class="glyphicon glyphicon-plus"></span>&nbsp;Add Customer Price</a>

    @(Html.Kendo().Grid<NuIngredient.Models.FruitProductExclusivePriceViewModel>()
            .Name("GridExclusivePrices")
            .Pageable(p => p.PageSizes(new[] { 25, 50, 100 }).Messages(m => m.Display("{0} - {1} of {2} Customter Prices").Empty("No Customter Prices Found")))
            .Columns(columns =>
            {
                columns.Bound(m => m.ID).Hidden();
                columns.Bound(m => m.ProductID).Hidden();
                columns.Bound(m => m.Customer).Title("Customer").ClientTemplate("#=Customer.Name#").EditorTemplateName("CustomerDropDown");
                columns.Bound(m => m.Price).Title("Customter Price").ClientTemplate("#=kendo.toString(Price, 'c')#").Width("1%");
                columns.Command(command =>
                {
                    command.Edit().Text("<span class='glyphicon glyphicon-edit glyphicon-btn'/>").UpdateText("<span class='glyphicon glyphicon-ok glyphicon-btn'/>").CancelText("<span class='glyphicon glyphicon-remove glyphicon-btn'/>");
                    command.Destroy().Text("<span class='glyphicon glyphicon-trash glyphicon-btn'/>");
                }).Width("90px");
            })
            .Editable(editable => editable.Mode(GridEditMode.InLine).ConfirmDelete("Are you sure you want to delete this item?"))
            .Sortable()
            .DataSource(dataSource => dataSource
                .Ajax()
                .Model(model =>
                {
                    model.Id(m => m.ID);
                    model.Field(m => m.ProductID).DefaultValue(Model.ID.ToString());
                    model.Field(m => m.Customer).DefaultValue(new NuIngredient.Models.SelectItemViewModel() { ID = "", Name = "" });
                })
                .Create(create => create.Action("Create", "FruitProductExclusivePriceGrid"))
                .Read(read => read.Action("Read", "FruitProductExclusivePriceGrid", new { productID = Model.ID }))
                .Update(update => update.Action("Update", "FruitProductExclusivePriceGrid"))
                .Destroy(destroy => destroy.Action("Destroy", "FruitProductExclusivePriceGrid"))
            )
            .Events(events => events.DataBound("KendoGridDatabound"))
    )

    <br />
    <br />
    <br />

OfficeGroceries.Admin/Views/FruitProductManagement/_Edit.cshtml
@model NuIngredient.Models.EditFruitProductViewModel

<script>
    function OnSuccess(response) {
        Refresh();
    }
    function OnProductImageUploadSuccess(e) {
            if (e.response.status == "error") {
                alert("Error: " + e.response.message);
            }
            else if (e.response.status == "success") {
                Refresh();
                EditFruit(e.response.id);
            }
    }

    function OnProductImageUpload(e) {
        var files = e.files;
        $.each(files, function () {
            if (this.size / 1024 / 1024 > 10) {
                alert("Max 1Mbs file size is allowed!")
                e.preventDefault();
            }
        });
    }

    function RemoveProductImage(id) {
        $.ajax({
            url: '@Url.Action("RemoveProductImage", "FruitProductManagement")',
            type: 'POST',
            data: { "id": id },
            dataType: "json",
            success: function (data) {
                Refresh();
                EditFruit(id);
            }
        });
    }
</script>

<div id="divEditProduct">

    @using (Ajax.BeginForm("_Edit", "FruitProductManagement", null, new AjaxOptions { UpdateTargetId = "divEditProduct", OnSuccess = "OnSuccess" }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        //@Html.ValidationSummary(false, "", new { @class = "alert alert-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="row">
            <div class="col-xs-9">
                <h2>Edit Product</h2>
            </div>
            <div class="col-xs-3">
                <br />
                <a class="btn btn-sm btn-default" onclick="HideViews(); return false;" style="float:right;"><span class="glyphicon glyphicon-remove"></span>&nbsp;Close</a>
            </div>
            <div class="col-xs-12">
                <br />
            </div>
            <div class="col-xs-4">

                @if ((Model.ImageURL ?? "") == "" || Model.ImageURL.Contains("NotFound"))
                {
                    <label>Upload Product Image:</label>
                    @(Html.Kendo().Upload().Multiple(false)
                                .Name("uploadedProductImage")
                                .Async(a => a.Save("UploadProductImage", "FruitProductManagement", new { id = Model.ID }))
                                .ShowFileList(false)
                                .HtmlAttributes(new { accept = "image/*" })
                                .Events(events => events.Upload("OnProductImageUpload").Success("OnProductImageUploadSuccess"))
                    )
                    <span style="font-size:x-small">Max 512Kbs</span>
                }
                else
                {
                    <a id="fruitTypeImage_link" class="fancybox-media" target="_blank" href="@Model.ImageURL">
                        <img id="fruitTypeImage" src="@Model.ImageURL" style="max-height:100px; max-width:300px; " />
                    </a>
                    <br />
                            <a href="#" onclick="RemoveProductImage('@Model.ID')">Remove Image</a>
                }
            </div>


        </div>

        @Html.Partial("_EditDetails", Model, new ViewDataDictionary() { { "SubmitValue", "Save Details" } })

        if (ViewBag.Saved ?? false)
        {
            <label id="l_Saved"><strong>Details Saved!</strong></label>
            <script>
                setTimeout(function () { $("#l_Saved").css("display", "none"); }, 2000);
            </script>
        }

        <div class="col-sm-12">
            <br />
            @(Html.Kendo().TabStrip()
                          .Scrollable(false)
                          .Name("Product_Tabstrip")
                          .Items(tabstrip =>
                          {
                              tabstrip.Add().Text("Prices").Content(@Html.Partial("_PricesTab", Model).ToHtmlString()).Selected(true);
                              tabstrip.Add().Text("Customer Prices").Content(@Html.Partial("_CustomerPricesTab", Model).ToHtmlString()).Selected(false);
                              tabstrip.Add()
                                  .Text("Tag Prices")
                                  .Content(@Html.Partial("_TagPricesTab", Model).ToHtmlString());
                              tabstrip.Add()
                                  .Text("Excluded Customers")
                                  .Content(@Html.Partial("_ExcludedCustomersTab", Model).ToHtmlString());
                          })
            )
        </div>
    }
</div>

OfficeGroceries.Admin/Views/FruitProductManagement/_New.cshtml
@model NuIngredient.Models.EditFruitProductViewModel

<div id="divNewProduct">

    @using (Ajax.BeginForm("_New", "FruitProductManagement", null, new AjaxOptions { UpdateTargetId = "divNewProduct", OnSuccess = "OnSuccess" }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        //@Html.ValidationSummary(false, "", new { @class = "alert alert-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="row">
            <div class="col-xs-9">
                <h2>New Fruit</h2>
            </div>
            <div class="col-xs-3">
                <br />
                <a class="btn btn-sm btn-default" onclick="HideViews(); return false;" style="float:right;"><span class="glyphicon glyphicon-remove"></span>&nbsp;Close</a>
            </div>
        </div>

        @Html.Partial("_EditDetails", Model, new ViewDataDictionary() { { "SubmitValue", "Add Product" } })
    }

    <script>
        function OnSuccess(response) {
            //Call function from Index view
            if (response["ID"] != null) {
                CreatedFruit(response["ID"]);
            }
        }
    </script>
</div>