OfficeGroceries/Controllers/Feedback/FeedbacksController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using NuIngredient.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System.Web.Routing;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.IO;
using Kendo.Mvc;
using System.Net.Mail;
using NuIngredient.Models.Extenstions;

namespace NuIngredient.Controllers
{
    [Authorize]
    public class FeedbacksController : BaseController
    {

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult _EditFeedback(Guid feedbackID)
        {
            var repo = new FeedbackRepository();
            var mapper = new FeedbackMapper();
            var model = repo.Find(feedbackID);
            var viewModel = mapper.MapToViewModel(model);
            return PartialView(viewModel);
        }

        [HttpPost]
        public ActionResult _EditFeedback(FeedbackViewModel viewModel)
        {
            var repo = new FeedbackRepository();
            var mapper = new FeedbackMapper();

            var model = repo.Find(Guid.Parse(viewModel.ID));
            mapper.MapToModel(viewModel, model);
            model.ReplierID = CurrentUser.Id;
            repo.Update(model, new string[] { "NIComment", "ReplierID", "ResponseTime" });

            ViewBag.Saved = true;

            return PartialView(mapper.MapToViewModel(model));
        }

        [HttpPost]
        public ActionResult Feedback(int type, string message, string dryGoodsOrderID)
        {
            var feedback = new Feedback()
            {
                FeedbackTypeID = type,
                Message = message,
                CompanyID = CurrentUser.CompanyID,
                UserID = CurrentUser.Id,
                DryGoodsOrderID = (type == FeedbackTypeValues.DryGoods && !string.IsNullOrWhiteSpace(dryGoodsOrderID)) ? Guid.Parse(dryGoodsOrderID) : null as Guid?,
            };

            using (var context = new SnapDbContext())
            {
                context.Feedbacks.Add(feedback);
                context.SaveChanges();
            }

            SendFeedbackMail(feedback.ID);

            return Json(new { Success = true, Message = "Message has been sent successfully, one of our specialists will be in contact with you shortly." });
        }

        private bool SendFeedbackMail(Guid feedbackID)
        {
            using (var context = new SnapDbContext())
            {
                var feedback = context.Feedbacks.Where(x => x.ID == feedbackID).First();
                var mailServer = context.EmailSettings.First();
                var overallSetting = context.Settings.First();

                MailMessage mailMessage = new MailMessage();
                mailMessage.Subject = String.Format("Feedback from " + feedback.Company.Name);
                mailMessage.AddToEmails(overallSetting.FeedbackCenterEmail);
                mailMessage.From = new MailAddress(mailServer.Email);
                mailMessage.Body = String.Format("<div class=\"row\" style='max-width: 500px;'>" +
                                                    "Customer Feedback" +
                                                    "<hr />" +
                                                    "<table>" +
                                                        "<tr>" +
                                                            "<td><label>Company:</label></td><td>{0}</td>" +
                                                        "</tr>" +
                                                        "<tr>" +
                                                            "<td><label>Name:</label></td><td>{1}</td>" +
                                                        "</tr>" +
                                                        "<tr>" +
                                                            "<td><label>Email:</label><td>{2}</td>" +
                                                        "</tr>" +
                                                        "<tr>" +
                                                            "<td><label>Telephone:</label><td>{3}</td>" +
                                                        "</tr>" +
                                                        "<tr>" +
                                                            "<td><label>Message:</label><td>{4}</td>" +
                                                        "</tr>" +
                                                        "<tr>" +
                                                            "<td><label>Timestamp:</label><td>{5}</td>" +
                                                        "</tr>" +
                                                    "</table>" +
                                                    "<hr />" +
                                                "</div>", feedback.Company.Name
                                                        , feedback.User.FirstName + " " + feedback.User.LastName
                                                        , feedback.User.Email
                                                        , feedback.User.PhoneNumber
                                                        , feedback.Message
                                                        , feedback.Created);
                mailMessage.IsBodyHtml = true;

                // Send to feedback center

                EmailService.SendEmail(mailMessage, Server);

                return true;
            }
        }
    }

}

OfficeGroceries/Controllers/Feedback/FeedbacksGridController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using NuIngredient.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System.Web.Routing;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.IO;
using Kendo.Mvc;
using System.Net.Mail;
using System.Text;

namespace NuIngredient.Controllers
{
    public class FeedbacksGridController : GridController<Feedback, FeedbackGridViewModel>
    {
        public FeedbacksGridController()
            : base(new FeedbackRepository(), new FeedbackGridMapper())
        {

        }

        [HttpPost]
        public JsonResult Read([DataSourceRequest] DataSourceRequest request, string filterText, Guid? companyID, string userID, int dateType, DateTime? fromDate, DateTime? toDate, bool showCompleted)
        {
            var viewModels = ReadFeedBacks(filterText, companyID, userID, dateType, fromDate, toDate, showCompleted);
            return Json(viewModels.ToDataSourceResult(request));
        }

        public ActionResult Export([DataSourceRequest] DataSourceRequest request, string filterText, Guid? companyID, string userID, int dateType, DateTime? fromDate, DateTime? toDate, bool showCompleted)
        {
            var viewModels = ReadFeedBacks(filterText, companyID, userID, dateType, fromDate, toDate, showCompleted);

            StringBuilder builder = new StringBuilder();
            builder.Append(string.Format("\"{0}\",\"{1}\",\"{2}\",\"{3}\",\"{4}\",\"{5}\",\"{6}\",\"{7}\"\n",
                    "Type", "Customer", "User", "Message", "Time", "Replyer", "Comment", "Response Time"
                ));

            // Append to StringBuilder.
            foreach (var q in viewModels)
            {
                builder.Append(string.Format("\"{0}\",\"{1}\",\"{2}\",\"{3}\",\"{4}\",\"{5}\",\"{6}\",\"{7}\"\n",
                        q.FeedbackType.Name,
                        q.CompanyName,
                        q.UserName,
                        q.Message,
                        q.Created.ToString("dd/MM/yyyy HH:mm"),
                        q.Replier,
                        q.NIComment,
                        q.ResponseTime != null ? q.ResponseTime.Value.ToString("dd/MM/yyyy HH:mm") : ""
                        ));
            }

            var fileContent = Encoding.ASCII.GetBytes(builder.ToString());
            var contentType = "text/csv";
            var fileDownloadName = string.Format("Feedback Export {0}.csv", DateTime.Today.ToString("dd-MM-yyyy"));

            return File(fileContent, contentType, fileDownloadName);
        }

        [HttpPost]
        public List<FeedbackGridViewModel> ReadFeedBacks(string filterText, Guid? companyID, string userID, int dateType, DateTime? fromDate, DateTime? toDate, bool showCompleted)
        {
            switch (dateType)
            {
                case 1: //Current Month
                    fromDate = DateTime.Today.AddDays(1 - (int)DateTime.Today.Day);
                    toDate = fromDate.Value.AddMonths(1);
                    break;
                case 2: //Last Month
                    fromDate = DateTime.Today.AddDays(1 - (int)DateTime.Today.Day).AddMonths(-1);
                    toDate = fromDate.Value.AddMonths(1);
                    break;
                case 3: //Custom Date
                    fromDate = fromDate.Value.Date;
                    toDate = toDate.Value.AddDays(1);
                    break;
                default:
                    toDate = DateTime.Today.AddYears(20);
                    fromDate = DateTime.Today.AddYears(-20);
                    break;
            }
            var viewModels = _repo.Read()
                              .Where(x => companyID == null || x.CompanyID == companyID)
                              .Where(x => userID == "" || x.UserID == userID)
                              .Where(x => x.Created >= fromDate && x.Created < toDate)
                              .Where(x => showCompleted == true || x.ResponseTime == null)
                              .Where(x => filterText == null
                                       || filterText == ""
                                       || x.Company.Name.ToLower().Contains(filterText.ToLower())
                                       || (x.User.FirstName.ToLower() + " " + x.User.LastName.ToLower()).Contains(filterText.ToLower())
                                       || x.Message.ToLower().Contains(filterText.ToLower()))
                              .OrderByDescending(x => x.Created)
                              .ToList()
                              .Select(x => _mapper.MapToViewModel(x));
            return viewModels.ToList();
        }
    }

}

OfficeGroceries/Views/Feedbacks/_EditFeedback.cshtml
@model NuIngredient.Models.FeedbackViewModel

<div id="divEditFeedback">

    <div class="row">
        <div class="col-sm-12">
            @using (Ajax.BeginForm("_EditFeedback", "Feedbacks", null, new AjaxOptions { UpdateTargetId = "divEditFeedback" }, new { id = "EditFeedbackForm", method = "post" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(m => m.ID)
                <div class="row">
                    <div class="col-sm-6">
                        <h2>Feedback</h2>
                    </div>
                    <div class="col-sm-6">
                        <br />
                        <div class="pull-right">
                            <input type="submit" value="Save Details" class="btn btn-sm btn-inverse">
                            <a class="btn btn-sm btn-default" onclick="HideViews(); return false;"><span class="glyphicon glyphicon-remove"></span>&nbsp;Close</a>
                            @if (ViewBag.Saved != null)
                            {
                                <br />
                                <label id="l_Saved"><strong>Details Saved!</strong></label>
                                <script>
                                    setTimeout(function () { $("#l_Saved").css("display", "none"); }, 2000);
                                </script>

                            }
                        </div>
                    </div>
                </div>
                <div class="row">   
                    <div class="col-sm-12"><br /></div>   
                    
                    <div class="col-sm-12">
                        <table class="table">
                            <tr>
                                <td><label>Customer:</label></td>
                                <td>@Model.CompanyName</td>
                            </tr>
                            <tr>
                                <td><label>User:</label></td>
                                <td>@Model.UserName</td>
                            </tr>
                            <tr>
                                <td><label>Type:</label></td>
                                <td><div class="label" style="background-color: @Model.FeedbackType.Colour">@Model.FeedbackType.Name</div></td>
                            </tr>
                            @if (Model.FeedbackTypeID == NuIngredient.Models.FeedbackTypeValues.DryGoods)
                            {
                            <tr>
                                <td><label>Order No:</label></td>
                                <td>@if (Model.DryGoodsOrder != null) { <text> @Model.DryGoodsOrder.OrderNumber </text> }</td>
                            </tr>
                            }
                            <tr>
                                <td><label>Time:</label></td>
                                <td>@Model.Created</td>
                            </tr>
                            <tr>
                                <td><label>Message:</label></td>
                                <td style = "white-space: pre-wrap;">@Html.Encode(Model.Message)</td>
                            </tr>
                            <tr>
                                <td><label>Comment:</label></td>
                                <td>@Html.TextAreaFor(model=> model.NIComment, 5, 90, new { @style = "max-width: 500px; "} )</td>
                            </tr>
                            <tr>
                                <td><label>Replyer:</label></td>
                                <td>@Model.Replier</td>
                            </tr>
                            <tr>
                                <td><label>Repsponse Time:</label></td>
                                <td>@if (Model.ResponseTime.HasValue) { <text> <div class="label label-warning">@Model.ResponseTime.Value.ToString("dd/MM/yyyy HH:mm")</div> </text> }</td>
                            </tr>
    
                            </table>
    
                        </div>
    

                        <div class="col-sm-12">
                        <hr />

                    </div>

                </div>

            }

        </div>

    </div>
</div>

<script>
    function OnEditCompanySuccess() {
        var url = '@Url.Action("_EditCompany", "Companies")' + '?ID=' + '@Model.ID';
        $("#Edit_Body").load(url);
    }
</script>